### ISSUE TITLE
Работа на Python/Django?

### ISSUE THREAD

**Issue by sg2018rm** [13g10n/crypto#3]
Здравствуйте, Иван,
извините что пишу вам в issue в github :) Если вам было бы интересно поработать над стартапами на Django (а у вас вроде есть опыт :)) И вы разговариваете по-английски И обладаете хотя бы базовыми знаниями js :), свяжитесь, пожалуйста, со мной в скайпе - sg2017rm@gmail.com (именно такой скайп). Или просто закройте issue если нет.
Спасибо за ваше время.

**Comment by 13g10n** [comment]
Спасибо за предложение, было бы очень интересно, но, к сожалению, на данный момент я уже работаю.
